name: Linting

on: [push, pull_request]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: 3.11

    - name: Install Poetry
      run: pip install uv

    - name: Install dependencies
      run: uv sync

    - name: Run Ruff
      run: uv run ruff check crudadmin