name: Type Checking

on: [push, pull_request]

jobs:
  type-check:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: 3.11

    - name: Install Poetry
      run: pip install uv

    - name: Install dependencies
      run: uv sync

    - name: Install mypy 1.9.0
      run: uv add mypy==1.9.0

    - name: Run mypy
      run: uv run mypy fastcrud --config-file mypy.ini